# Limpieza de Datos

In [1]:
import pandas as pd
import os

In [2]:
archivo = "GSAF5.xls"

In [ ]:
if os.path.exists(archivo):
    df = pd.read_excel(archivo)
    print("¡Archivo cargado!")
    display(df.head())
else:
    print(f"Error: No se encontró el archivo '{archivo}' en el directorio actual.")

¡Archivo cargado!

In [6]:
# Establezco el límite de columnas mostradas
pd.set_option('display.max_columns', None)
df.head()

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,Injury,Fatal Y/N,Time,Species,Source,pdf,href formula,href,Case Number,Case Number.1,original order,Unnamed: 21,Unnamed: 22
0,29th January,2026.0,Unprovoked,Brazil,Recife,Del Chifre Beach in Olinda,Swimming,Deivson Rocha Dantas,M,13,Right thigh and lower leg stripped of flesh,Y,?,Unknown bull and tiger sharks frequent the area,Kevin McMurray Trackingsharks.com: TV Globo: P...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,29th January,2026.0,Unprovoked,Australia,NSW,Angels Beach East Ballina,Surfing,Unnamed man,M,?,No injury shark knocked man of his board,N,1100hrs,Unknown,Bob Myatt GSAF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,24th January,2026.0,Unprovoked,Australia,Tasmania,Cooee Beach west of Burnie,Swimming,Megan Stokes,F,?,Puncture wounds to right knee,N,1815hrs,1.7m Seven Gill shark,Bob Myatt GSAF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,20th January,2026.0,Unprovoked,Australia,NSW,Point Plomber North of Port Macquarie,Surfing,Paul Zvirdinas,M,39,Minor cuts and abrasions,N,0830hrs,Bull shark,Bob Myatt GSAF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,19th January,2026.0,Unprovoked,Australia,NSW,Dee Why,Surfing,Unknown,M,11,None reported damage to board,N,1145hrs,Bull shark,Andy Currie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7074 entries, 0 to 7073
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            7074 non-null   object
 1   Year            7072 non-null   float64
 2   Type            7056 non-null   str
 3   Country         7024 non-null   str
 4   State           6587 non-null   str
 5   Location        6507 non-null   str
 6   Activity        6491 non-null   str
 7   Name            6856 non-null   str
 8   Sex             6496 non-null   str
 9   Age             4080 non-null   object
 10  Injury          7039 non-null   str
 11  Fatal Y/N       6513 non-null   object
 12  Time            3547 non-null   object
 13  Species         3943 non-null   str
 14  Source          7054 non-null   object
 15  pdf             6799 non-null   object
 16  href formula    6794 non-null   str
 17  href            6796 non-null   str
 18  Case Number     6798 non-null   str
 19  Case Number.1   6797 non-null   str
 20  original order  6799 non-null   float64
 21  Unnamed: 21     1 non-null      str
 22  Unnamed: 22     2 non-null      str
dtypes: float64(2), object(6), str(15)
memory usage: 1.2+ MB

In [10]:
# Elimino columnas con casi todo nulos
df1 = df.drop(columns=['Unnamed: 21', 'Unnamed: 22'])

In [14]:
df1.isnull().sum().sort_values(ascending=False)

Time              3527
Species           3131
Age               2994
Activity           583
Sex                578
Location           567
Fatal Y/N          561
State              487
href formula       280
href               278
Case Number.1      277
Case Number        276
pdf                275
original order     275
Name               218
Country             50
Injury              35
Source              20
Type                18
Year                 2
Date                 0
dtype: int64

Se observan campos con gran cantidad de nulos, aunque no serían los de mayor interés para el análisis actual.
Seguidamente analizamos porcentualmente la incidencia de nulos para saber el impacto en el error que pudiera introducir debido a información faltante.

In [15]:
# Porcentaje de nulos por columna
porcentaje_nulos = (df1.isnull().sum() / len(df1)) * 100
print(porcentaje_nulos.sort_values(ascending=False))

Time              49.858637
Species           44.260673
Age               42.324003
Activity           8.241448
Sex                8.170766
Location           8.015267
Fatal Y/N          7.930450
State              6.884365
href formula       3.958157
href               3.929884
Case Number.1      3.915748
Case Number        3.901612
pdf                3.887475
original order     3.887475
Name               3.081708
Country            0.706814
Injury             0.494770
Source             0.282725
Type               0.254453
Year               0.028273
Date               0.000000
dtype: float64

Afortunadamente, el impacto en los campos de mayor interés (Country y Type) es mínimo.

### Campo Year

In [ ]:
# Convertir a entero 
df1['Year'] = df1['Year'].astype('Int64')
df1[['Year']].head()

Int64

   Year
0  2026
1  2026
2  2026
3  2026
4  2026

Ahora analizamos posibles años extraños o cargados con error.

In [24]:
df1[df1['Year'] < 1500][['Country','Type','Location','Year']]

,Country,Type,Location,Year
6942,USA,Unprovoked,Archeological site,1000
6943,NaN,Unprovoked,NaN,77
6944,AUSTRALIA,Unprovoked,Bondi,5
6945,NaN,Unprovoked,NaN,0
6946,GREECE,Unprovoked,In the haven of Cantharus,0
...,...,...,...,...
7069,AUSTRALIA,Unprovoked,Roebuck Bay,0
7070,AUSTRALIA,Unprovoked,NaN,0
7071,USA,Unprovoked,Ocracoke Inlet,0
7072,PANAMA,Unprovoked,"Panama Bay 8ºN, 79ºW",0
7073,CEYLON (SRI LANKA),Unprovoked,"Below the English fort, Trincomalee",0

### Campo Country
Será necesario eliminar los Country='NaN'

In [27]:
# Borrar filas donde la columna Country sea nula
df1.dropna(subset=['Country'], inplace=True)

De igual manera procedemos con campo 'Type' cuya baja incidencia de NaN lo hace posible.

In [32]:
# Quitar espacios al en los extremos y poner primera letra en mayúsculas
df1['Country'] = df1['Country'].str.strip().str.capitalize()

In [33]:
# Vemos los 20 Country más frecuentes
print(df1['Country'].value_counts().head(20))

Country
Usa                 2571
Australia           1521
South africa         598
New zealand          146
Bahamas              141
Papua new guinea     136
Brazil               123
Mexico               107
Italy                 72
Fiji                  70
New caledonia         67
Philippines           65
Reunion               60
Egypt                 52
Mozambique            50
Cuba                  49
Spain                 47
India                 41
French polynesia      40
Japan                 35
Name: count, dtype: int64

### Campo Type
La tabla top anterior luce bien en cuanto a los principales países.

In [30]:
# Borrar filas donde la columna Type sea nula
df1.dropna(subset=['Type'], inplace=True)

In [34]:
# Quitar espacios al en los extremos y poner primera letra en mayúsculas
df1['Type'] = df1['Type'].str.strip().str.capitalize()

In [35]:
# Vemos los Type más frecuentes
print(df1['Type'].value_counts().head(20))

Type
Unprovoked             5193
Provoked                641
Invalid                 547
Watercraft              354
Sea disaster            234
Questionable             26
Boat                      7
?                         1
Unconfirmed               1
Unverified                1
Under investigation       1
Name: count, dtype: int64